## Pandas - Importing data

Please download the following data and move it to an appropriate folder:

- <a href="https://drive.google.com/file/d/1gVDDJg3Ngnz8h9f2pX9AcdgWgx5zkV6U/view?usp=sharing">Bridge Inspections excerpt</a>.

In [2]:
## import the pandas library in this cell
import pandas as pd

### Ingest the following dataset into this note:

In [14]:
## import data and store in dataframe call dfbi (short perhaps for dataframe bridge inspections)
df = pd.read_csv("bridge-inspections-excerpt.csv")

df

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
0,47,189,'BRANCH',35595580.0,86115051.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,5,NaN
1,47,189,'BRANCH',35575281.0,86103402.0,2.0,8.0,1930.0,2,19.0,N,N,N,7,7,NaN
2,47,189,'BRANCH',36062250.0,86245507.0,2.0,8.0,1935.0,2,19.0,N,N,N,7,5,NaN
3,47,189,'OVERFLOW',36060931.0,86245689.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,7,NaN
4,47,189,'HURRICANE CREEK',36031626.0,86251979.0,2.0,8.0,1970.0,3,2.0,6,5,5,8,N,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,53,39,'TROUT CREEK',45595604.0,121314080.0,2.0,7.0,1956.0,2,1.0,6,6,5,8,N,NaN
99996,53,65,'COLVILLE RIVER',48103246.0,117434719.0,2.0,7.0,1960.0,3,2.0,5,6,6,8,N,NaN
99997,53,77,'DRAIN',46195400.0,120161800.0,2.0,9.0,1965.0,7,2.0,7,4,4,8,N,NaN
99998,53,53,'LEACH CREEK',47122326.0,122305265.0,4.0,14.0,1981.0,3,19.0,N,N,N,8,7,NaN
99999,53,75,'SOUTH FORK PALOUSE RIVER',46461734.0,117141254.0,2.0,9.0,1963.0,5,4.0,5,6,7,7,N,NaN

In [15]:
## call the first 10 rows
df.head(10)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
0,47,189,'BRANCH',35595580.0,86115051.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,5,NaN
1,47,189,'BRANCH',35575281.0,86103402.0,2.0,8.0,1930.0,2,19.0,N,N,N,7,7,NaN
2,47,189,'BRANCH',36062250.0,86245507.0,2.0,8.0,1935.0,2,19.0,N,N,N,7,5,NaN
3,47,189,'OVERFLOW',36060931.0,86245689.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,7,NaN
4,47,189,'HURRICANE CREEK',36031626.0,86251979.0,2.0,8.0,1970.0,3,2.0,6,5,5,8,N,NaN
5,47,189,'PURTLE CREEK',36000534.0,86024153.0,2.0,8.0,1995.0,2,19.0,N,N,N,8,6,NaN
6,47,189,'GOOSE CREEK',36035202.0,86033583.0,2.0,8.0,1960.0,2,4.0,7,6,6,6,N,NaN
7,47,189,'GOOSE CREEK',36033059.0,86040120.0,2.0,8.0,1965.0,2,19.0,N,N,N,6,6,NaN
8,47,189,'BRANCH',36014830.0,86030353.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,6,NaN
9,47,189,'PURTLE CREEK',36004548.0,86023480.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,6,NaN

In [16]:
## call the last 5 rows
df.tail(5)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
99995,53,39,'TROUT CREEK',45595604.0,121314080.0,2.0,7.0,1956.0,2,1.0,6,6,5,8,N,NaN
99996,53,65,'COLVILLE RIVER',48103246.0,117434719.0,2.0,7.0,1960.0,3,2.0,5,6,6,8,N,NaN
99997,53,77,'DRAIN',46195400.0,120161800.0,2.0,9.0,1965.0,7,2.0,7,4,4,8,N,NaN
99998,53,53,'LEACH CREEK',47122326.0,122305265.0,4.0,14.0,1981.0,3,19.0,N,N,N,8,7,NaN
99999,53,75,'SOUTH FORK PALOUSE RIVER',46461734.0,117141254.0,2.0,9.0,1963.0,5,4.0,5,6,7,7,N,NaN

In [19]:
## call a 20 random rows
df.sample(20)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
19936,48,73,'COOKE CREEK',31500216.0,95002440.0,1.0,7.0,1967.0,1,19.0,N,N,N,6,6,NaN
53826,48,61,'SPUR 54',26114337.0,97431135.0,1.0,12.0,1971.0,5,2.0,7,7,7,N,N,NaN
72214,49,11,'I-215 (SR-215) EBL/WBL',10500204.0,111560600.0,1.0,14.0,2018.0,2,2.0,7,8,7,N,N,1.0
41076,48,297,'RAMIRENA CREEK',28070614.0,98161514.0,2.0,9.0,1940.0,3,2.0,7,6,6,6,N,NaN
39898,48,325,'HONDO CREEK',29082529.0,99031981.0,1.0,7.0,1962.0,1,2.0,6,7,5,5,N,NaN
21946,48,347,'ANGELINA RIVER',31291351.0,94492391.0,1.0,6.0,2008.0,5,2.0,7,8,7,7,N,1.0
7789,48,439,'TRIB OF TRINITY RIVER',32501233.0,97055944.0,1.0,12.0,1968.0,1,19.0,N,N,N,7,6,NaN
26009,48,201,'Orem Dr',29373955.0,95231323.0,26.0,12.0,2020.0,5,2.0,7,7,8,N,N,NaN
48828,48,121,'HARRIET CREEK',33035456.0,97232880.0,2.0,9.0,2010.0,1,19.0,N,N,N,7,7,NaN
48013,48,113,'MAUK CREEK',32383983.0,96545963.0,4.0,17.0,1988.0,1,19.0,N,N,N,7,7,NaN
2817,47,157,'LONG RD',35181590.0,89415071.0,NaN,19.0,1996.0,6,2.0,NaN,NaN,NaN,NaN,NaN,NaN
43751,48,477,'SANDY CREEK',30091321.0,96282557.0,2.0,9.0,2015.0,3,2.0,7,7,6,6,N,NaN
86803,51,149,'APPOMATTOX RV & SERV RD',37185575.0,77200340.0,1.0,11.0,1991.0,3,2.0,7,7,6,7,N,2.0
65840,48,29,'Marbach Rd.',29250261.0,98385901.0,NaN,16.0,2019.0,5,2.0,NaN,NaN,NaN,NaN,NaN,NaN
72730,49,57,'I-15 (SR-15) NBL & S',41121045.0,111593830.0,NaN,1.0,1967.0,3,3.0,NaN,NaN,NaN,NaN,NaN,NaN
2363,47,145,'I40 RT LN / SR 61',35543612.0,84352165.0,NaN,14.0,1969.0,4,2.0,NaN,NaN,NaN,NaN,NaN,NaN
68928,48,61,'FM 511',25570872.0,97245444.0,NaN,14.0,1993.0,5,2.0,NaN,NaN,NaN,NaN,NaN,NaN
77300,51,5,'POTTS CREEK',37440560.0,80015656.0,1.0,7.0,1954.0,3,2.0,6,6,6,6,N,NaN
29932,48,89,'DOWDY CREEK',29391287.0,96402396.0,2.0,9.0,1969.0,5,5.0,8,6,7,7,N,NaN
8060,48,439,'TRIB TO DEER CREEK',32343993.0,97191755.0,1.0,14.0,1976.0,1,19.0,N,N,N,6,7,NaN

In [21]:
## get basic overview of the data
## what datatypes do the different columns hold?
## how many rows and columns are there

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 16 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   STATE_CODE_001           100000 non-null  int64
 1   COUNTY_CODE_003          100000 non-null  int64
 2   FEATURES_DESC_006A       100000 non-null  str
 3   LAT_016                  99493 non-null   float64
 4   LONG_017                 99486 non-null   float64
 5   OWNER_022                82621 non-null   float64
 6   FUNCTIONAL_CLASS_026     99660 non-null   float64
 7   YEAR_BUILT_027           99997 non-null   float64
 8   STRUCTURE_KIND_043A      100000 non-null  int64
 9   STRUCTURE_TYPE_043B      99999 non-null   float64
 10  DECK_COND_058            82621 non-null   str
 11  SUPERSTRUCTURE_COND_059  82621 non-null   str
 12  SUBSTRUCTURE_COND_060    82621 non-null   str
 13  CHANNEL_COND_061         82621 non-null   str
 14  CULVERT_COND_062         82621 non-null   str
 15  PIER_PROTECTION_111      4353 non-null    float64
dtypes: float64(7), int64(3), str(6)
memory usage: 12.2 MB

### Which column has the most missing data...just a quick estimate? 
Pier Protection

In [22]:
## call the top 7 rows
df.head(7)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
0,47,189,'BRANCH',35595580.0,86115051.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,5,NaN
1,47,189,'BRANCH',35575281.0,86103402.0,2.0,8.0,1930.0,2,19.0,N,N,N,7,7,NaN
2,47,189,'BRANCH',36062250.0,86245507.0,2.0,8.0,1935.0,2,19.0,N,N,N,7,5,NaN
3,47,189,'OVERFLOW',36060931.0,86245689.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,7,NaN
4,47,189,'HURRICANE CREEK',36031626.0,86251979.0,2.0,8.0,1970.0,3,2.0,6,5,5,8,N,NaN
5,47,189,'PURTLE CREEK',36000534.0,86024153.0,2.0,8.0,1995.0,2,19.0,N,N,N,8,6,NaN
6,47,189,'GOOSE CREEK',36035202.0,86033583.0,2.0,8.0,1960.0,2,4.0,7,6,6,6,N,NaN

In [23]:
## call a sample of 10
df.sample(10)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
17714,48,99,'TRIB LEON RIVER',31351043.0,97504081.0,1.0,6.0,1955.0,1,19.0,N,N,N,7,6,NaN
74455,50,19,'MISSISQUOI RIVER',44572279.0,72233660.0,3.0,9.0,1910.0,3,10.0,0,0,7,7,N,NaN
3201,47,187,'I840/ROBINSON RD & BR',35490096.0,87011655.0,NaN,9.0,2011.0,6,2.0,NaN,NaN,NaN,NaN,NaN,NaN
11192,48,487,'DRAW',34155580.0,99203723.0,2.0,9.0,2011.0,1,19.0,N,N,N,7,7,NaN
28917,48,339,'LOG GULLY',30102973.0,95465996.0,2.0,16.0,2018.0,5,2.0,8,8,7,8,N,1.0
35577,48,491,'DRY BERRY CREEK',30410595.0,97381330.0,2.0,9.0,2004.0,5,2.0,8,8,7,7,N,NaN
17404,48,27,'LTL ELM CRK BR #508 TEM',31043460.0,97172942.0,4.0,9.0,1978.0,1,19.0,N,N,N,5,6,NaN
11739,48,359,'Draw',35111872.0,102583605.0,1.0,1.0,1938.0,1,19.0,N,N,N,7,6,NaN
324,47,189,'SPENCE CREEK',36140438.0,86252202.0,1.0,14.0,2007.0,6,2.0,8,8,8,8,N,NaN
53873,48,61,'FM 511',26014486.0,97320008.0,1.0,12.0,1987.0,5,2.0,6,7,7,N,N,NaN

In [24]:
## call the bottom 6
df.tail(6)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
99994,53,61,'SWAMP CREEK',47482979.0,122152176.0,2.0,16.0,1963.0,1,22.0,7,7,5,6,N,NaN
99995,53,39,'TROUT CREEK',45595604.0,121314080.0,2.0,7.0,1956.0,2,1.0,6,6,5,8,N,NaN
99996,53,65,'COLVILLE RIVER',48103246.0,117434719.0,2.0,7.0,1960.0,3,2.0,5,6,6,8,N,NaN
99997,53,77,'DRAIN',46195400.0,120161800.0,2.0,9.0,1965.0,7,2.0,7,4,4,8,N,NaN
99998,53,53,'LEACH CREEK',47122326.0,122305265.0,4.0,14.0,1981.0,3,19.0,N,N,N,8,7,NaN
99999,53,75,'SOUTH FORK PALOUSE RIVER',46461734.0,117141254.0,2.0,9.0,1963.0,5,4.0,5,6,7,7,N,NaN

In [25]:
## call the year built column using dot notation
df.YEAR_BUILT_027

0        1965.0
1        1930.0
2        1935.0
3        1960.0
4        1970.0
          ...
99995    1956.0
99996    1960.0
99997    1965.0
99998    1981.0
99999    1963.0
Name: YEAR_BUILT_027, Length: 100000, dtype: float64

In [27]:
## call FEATURES_DESC_006A as a series using square bracket notation

df["FEATURES_DESC_006A"]

0                          'BRANCH'
1                          'BRANCH'
2                          'BRANCH'
3                        'OVERFLOW'
4                 'HURRICANE CREEK'
                    ...
99995                 'TROUT CREEK'
99996              'COLVILLE RIVER'
99997                       'DRAIN'
99998                 'LEACH CREEK'
99999    'SOUTH FORK PALOUSE RIVER'
Name: FEATURES_DESC_006A, Length: 100000, dtype: str

In [45]:
## what are the unique owner codes?
df["OWNER_022"].unique()

array([ 2.,  4.,  1.,  3., 79., 63., 67., 64., 70., 66., 72., 74., nan,
       68., 21., 80., 31., 32., 11., 40., 25., 26., 75., 12., 27., 55.,
       56., 69., 62., 73., 76., 54., 77.])

### What do these codes mean?

The codes represent all the possible values represented in the unique owner column.